"""create inventory schema

Revision ID: a2dc70ad62cc
Revises: 
Create Date: 2026-09-30 11:29:51.268584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2dc70ad62cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_businesses'))
    )
    op.create_table('categories',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_categories_business_id_businesses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('business_id', 'name', name='uq_categories_business_id_name')
    )
    op.create_table('locations',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_locations_business_id_businesses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('business_id', 'name', name='uq_locations_business_id_name')
    )
    op.create_table('suppliers',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_suppliers_business_id_businesses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_table('users',
    sa.Column('business_id', sa.CHAR(length=36), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invited_by_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IS NULL OR role IN ('owner', 'staff')", name=op.f('ck_users_role_known')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_users_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], name=op.f('fk_users_invited_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_log',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('actor_user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.CHAR(length=36), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'agent')", name=op.f('ck_audit_log_actor_type_known')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_audit_log_business_id_businesses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('products',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.CHAR(length=36), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('safety_stock', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_products_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('business_id', 'sku', name='uq_products_business_id_sku')
    )
    op.create_table('purchase_orders',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=32), nullable=False),
    sa.Column('supplier_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('currency_code', sa.CHAR(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_on', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'approved', 'sent', 'received', 'cancelled')", name=op.f('ck_purchase_orders_status_known')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_purchase_orders_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_purchase_orders_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_purchase_orders_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('business_id', 'po_number', name='uq_purchase_orders_business_id_po_number')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('token_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_table('product_suppliers',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_id', sa.CHAR(length=36), nullable=False),
    sa.Column('supplier_id', sa.CHAR(length=36), nullable=False),
    sa.Column('supplier_sku', sa.String(length=64), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('lead_time_days >= 0', name=op.f('ck_product_suppliers_lead_time_nonnegative')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_product_suppliers_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_suppliers_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_product_suppliers_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_suppliers')),
    sa.UniqueConstraint('product_id', 'supplier_id', name='uq_product_suppliers_product_id_supplier_id')
    )
    op.create_table('purchase_order_items',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('purchase_order_id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_id', sa.CHAR(length=36), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity_ordered > 0', name=op.f('ck_purchase_order_items_quantity_ordered_positive')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_purchase_order_items_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_items_purchase_order_id_purchase_orders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_items'))
    )
    op.create_table('stock_movements',
    sa.Column('business_id', sa.CHAR(length=36), nullable=False),
    sa.Column('product_id', sa.CHAR(length=36), nullable=False),
    sa.Column('location_id', sa.CHAR(length=36), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('transfer_group_id', sa.CHAR(length=36), nullable=True),
    sa.Column('sale_group_id', sa.CHAR(length=36), nullable=True),
    sa.Column('purchase_order_item_id', sa.CHAR(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.CheckConstraint("(movement_type = 'purchase_receipt' AND purchase_order_item_id IS NOT NULL) OR (movement_type != 'purchase_receipt' AND purchase_order_item_id IS NULL)", name=op.f('ck_stock_movements_receipt_links_po_item')),
    sa.CheckConstraint("(movement_type = 'sale' AND sale_group_id IS NOT NULL) OR (movement_type != 'sale' AND sale_group_id IS NULL)", name=op.f('ck_stock_movements_sale_group_iff_sale')),
    sa.CheckConstraint("(movement_type = 'transfer' AND transfer_group_id IS NOT NULL) OR (movement_type != 'transfer' AND transfer_group_id IS NULL)", name=op.f('ck_stock_movements_transfer_group_iff_transfer')),
    sa.CheckConstraint("movement_type != 'adjustment' OR (reason IS NOT NULL AND length(trim(reason)) > 0)", name=op.f('ck_stock_movements_adjustment_reason_nonblank')),
    sa.CheckConstraint("movement_type != 'purchase_receipt' OR quantity > 0", name=op.f('ck_stock_movements_receipt_quantity_positive')),
    sa.CheckConstraint("movement_type != 'sale' OR quantity < 0", name=op.f('ck_stock_movements_sale_quantity_negative')),
    sa.CheckConstraint("movement_type IN ('purchase_receipt', 'sale', 'adjustment', 'transfer')", name=op.f('ck_stock_movements_movement_type_known')),
    sa.CheckConstraint('quantity <> 0', name=op.f('ck_stock_movements_quantity_nonzero')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_stock_movements_business_id_businesses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_stock_movements_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_stock_movements_location_id_locations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_order_item_id'], ['purchase_order_items.id'], name=op.f('fk_stock_movements_purchase_order_item_id_purchase_order_items'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index('ix_stock_movements_on_hand', 'stock_movements', ['business_id', 'product_id', 'location_id'], unique=False)
    op.create_index('ix_stock_movements_purchase_order_item_id', 'stock_movements', ['purchase_order_item_id'], unique=False)
    op.create_index('ix_stock_movements_transfer_group_id', 'stock_movements', ['transfer_group_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_movements_transfer_group_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_purchase_order_item_id', table_name='stock_movements')
    op.drop_index('ix_stock_movements_on_hand', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('purchase_order_items')
    op.drop_table('product_suppliers')
    op.drop_table('refresh_tokens')
    op.drop_table('purchase_orders')
    op.drop_table('products')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('locations')
    op.drop_table('categories')
    op.drop_table('businesses')
    # ### end Alembic commands ###
